<?php

namespace Database\Seeders;

use App\Models\Item;
use App\Models\ItemPhoto;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'id'              => 1,
                'user_id'         => 1,
                'category_id'     => 1,
                'type'            => 'lost',
                'title'           => 'iPhone 14 Pro Deep Purple',
                'description'     => 'iPhone 14 Pro warna ungu tua, casing transparan, ada retak sedikit di tempered glass.',
                'location'        => 'Gedung A, Lt. 2, R.201',
                'location_detail' => null,
                'latitude'        => '-7.17560000',
                'longitude'       => '112.64920000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-04 15:31:33',
                'created_at'      => '2026-05-06 15:31:33',
                'updated_at'      => '2026-05-06 15:31:33',
                '_photos'         => ['items/item_1_iphone.jpg'],
            ],
            [
                'id'              => 2,
                'user_id'         => 2,
                'category_id'     => 1,
                'type'            => 'lost',
                'title'           => 'Laptop MacBook Air M1',
                'description'     => 'MacBook Air M1 warna Grey, ada stiker Apple Developer di cover depan.',
                'location'        => 'Perpustakaan Lt. 2',
                'location_detail' => null,
                'latitude'        => '-7.17580000',
                'longitude'       => '112.64900000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-05 15:31:33',
                'created_at'      => '2026-05-06 15:31:35',
                'updated_at'      => '2026-05-06 15:31:35',
                '_photos'         => ['items/item_2_macbook.jpg'],
            ],
            [
                'id'              => 3,
                'user_id'         => 1,
                'category_id'     => 1,
                'type'            => 'found',
                'title'           => 'AirPods Pro Gen 2',
                'description'     => 'AirPods Pro dengan case silikon warna hitam. Tertinggal di meja kantin.',
                'location'        => 'Kantin Utama',
                'location_detail' => null,
                'latitude'        => '-7.17600000',
                'longitude'       => '112.64880000',
                'storage_info'    => 'Disimpan Ibu Kantin',
                'status'          => 'active',
                'date_time'       => '2026-05-06 10:31:33',
                'created_at'      => '2026-05-06 15:31:36',
                'updated_at'      => '2026-05-06 15:31:36',
                '_photos'         => ['items/item_3_airpods.jpg'],
            ],
            [
                'id'              => 4,
                'user_id'         => 2,
                'category_id'     => 1,
                'type'            => 'found',
                'title'           => 'Powerbank Anker 20000mAh',
                'description'     => 'Powerbank besar warna hitam, agak berat. Ada kabel USB-C menempel.',
                'location'        => 'Musholla Kampus',
                'location_detail' => null,
                'latitude'        => '-7.17530000',
                'longitude'       => '112.64960000',
                'storage_info'    => 'Satpam Pos 1',
                'status'          => 'active',
                'date_time'       => '2026-05-06 03:31:33',
                'created_at'      => '2026-05-06 15:31:37',
                'updated_at'      => '2026-05-06 15:31:37',
                '_photos'         => ['items/item_4_powerbank.jpg'],
            ],
            [
                'id'              => 5,
                'user_id'         => 1,
                'category_id'     => 1,
                'type'            => 'lost',
                'title'           => 'Mouse Wireless Logitech',
                'description'     => 'Mouse Logitech M220 Silent warna merah.',
                'location'        => 'Lab Komputer 3',
                'location_detail' => null,
                'latitude'        => '-7.17540000',
                'longitude'       => '112.64930000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-03 15:31:33',
                'created_at'      => '2026-05-06 15:31:38',
                'updated_at'      => '2026-05-06 15:31:38',
                '_photos'         => ['items/item_5_computer_mouse.jpg'],
            ],
            [
                'id'              => 6,
                'user_id'         => 2,
                'category_id'     => 1,
                'type'            => 'found',
                'title'           => 'Kamera Canon DSLR',
                'description'     => 'Kamera Canon EOS tertinggal di bangku taman. Lensa kit 18-55mm.',
                'location'        => 'Taman Kampus Tengah',
                'location_detail' => null,
                'latitude'        => '-7.17570000',
                'longitude'       => '112.64910000',
                'storage_info'    => 'Pos Satpam Pusat',
                'status'          => 'active',
                'date_time'       => '2026-05-05 15:31:33',
                'created_at'      => '2026-05-06 15:31:41',
                'updated_at'      => '2026-05-06 15:31:41',
                '_photos'         => ['items/item_6_camera.jpg'],
            ],
            [
                'id'              => 7,
                'user_id'         => 1,
                'category_id'     => 1,
                'type'            => 'lost',
                'title'           => 'iPad Air 5 Blue',
                'description'     => 'iPad Air 5 warna biru dengan Apple Pencil Gen 2.',
                'location'        => 'Ruang Diskusi Perpustakaan',
                'location_detail' => null,
                'latitude'        => '-7.17580000',
                'longitude'       => '112.64900000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-06 13:31:33',
                'created_at'      => '2026-05-06 15:31:43',
                'updated_at'      => '2026-05-06 15:31:43',
                '_photos'         => ['items/item_7_ipad.jpg'],
            ],
            [
                'id'              => 8,
                'user_id'         => 2,
                'category_id'     => 1,
                'type'            => 'found',
                'title'           => 'Samsung Galaxy S23',
                'description'     => 'HP Samsung S23 warna Cream, casing bening.',
                'location'        => 'Toilet Gedung B',
                'location_detail' => null,
                'latitude'        => '-7.17550000',
                'longitude'       => '112.64940000',
                'storage_info'    => 'Satpam Gedung B',
                'status'          => 'active',
                'date_time'       => '2026-05-05 15:31:33',
                'created_at'      => '2026-05-06 15:31:46',
                'updated_at'      => '2026-05-06 15:31:46',
                '_photos'         => ['items/item_8_smartphone.jpg'],
            ],
            [
                'id'              => 9,
                'user_id'         => 1,
                'category_id'     => 2,
                'type'            => 'found',
                'title'           => 'KTM a.n. Siti Aminah',
                'description'     => 'Kartu Tanda Mahasiswa jurusan Manajemen angkatan 2023. Ditemukan di parkiran.',
                'location'        => 'Parkiran Motor Belakang',
                'location_detail' => null,
                'latitude'        => '-7.17520000',
                'longitude'       => '112.64950000',
                'storage_info'    => 'Satpam Parkir',
                'status'          => 'active',
                'date_time'       => '2026-05-05 15:31:33',
                'created_at'      => '2026-05-06 15:31:47',
                'updated_at'      => '2026-05-06 15:31:47',
                '_photos'         => ['items/item_9_id_card.jpg'],
            ],
            [
                'id'              => 10,
                'user_id'         => 2,
                'category_id'     => 2,
                'type'            => 'lost',
                'title'           => 'Dompet STNK & SIM',
                'description'     => 'Dompet kecil berisi STNK Motor NMAX L 4523 XY dan SIM C a.n. Budi Santoso.',
                'location'        => 'Sekitar Gerbang Keluar',
                'location_detail' => null,
                'latitude'        => '-7.17640000',
                'longitude'       => '112.64840000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-06 11:31:33',
                'created_at'      => '2026-05-06 15:31:49',
                'updated_at'      => '2026-05-06 15:31:49',
                '_photos'         => ['items/item_10_documents.jpg'],
            ],
            [
                'id'              => 11,
                'user_id'         => 1,
                'category_id'     => 2,
                'type'            => 'lost',
                'title'           => 'Berkas Skripsi Map Biru',
                'description'     => 'Map plastik biru berisi draft skripsi Bab 1-3. Penting banget!',
                'location'        => 'Meja Kantin Pojok',
                'location_detail' => null,
                'latitude'        => '-7.17600000',
                'longitude'       => '112.64880000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-06 14:31:33',
                'created_at'      => '2026-05-06 15:31:50',
                'updated_at'      => '2026-05-06 15:31:50',
                '_photos'         => ['items/item_11_folder_paper.jpg'],
            ],
            [
                'id'              => 12,
                'user_id'         => 2,
                'category_id'     => 2,
                'type'            => 'found',
                'title'           => 'Pasport Hijau',
                'description'     => 'Paspor ketinggalan di ruang tunggu rektorat.',
                'location'        => 'Lobi Rektorat',
                'location_detail' => null,
                'latitude'        => '-7.17560000',
                'longitude'       => '112.64920000',
                'storage_info'    => 'Resepsionis Rektorat',
                'status'          => 'active',
                'date_time'       => '2026-05-01 15:31:33',
                'created_at'      => '2026-05-06 15:31:52',
                'updated_at'      => '2026-05-06 15:31:52',
                '_photos'         => ['items/item_12_passport.jpg'],
            ],
            [
                'id'              => 13,
                'user_id'         => 1,
                'category_id'     => 2,
                'type'            => 'found',
                'title'           => 'Buku Tabungan BCA',
                'description'     => 'Buku tabungan BCA ditemukan di ATM Center kampus.',
                'location'        => 'ATM Center',
                'location_detail' => null,
                'latitude'        => '-7.17630000',
                'longitude'       => '112.64850000',
                'storage_info'    => 'Satpam ATM',
                'status'          => 'active',
                'date_time'       => '2026-05-06 07:31:33',
                'created_at'      => '2026-05-06 15:31:53',
                'updated_at'      => '2026-05-06 15:31:53',
                '_photos'         => ['items/item_13_bankbook.jpg'],
            ],
            [
                'id'              => 14,
                'user_id'         => 1,
                'category_id'     => 3,
                'type'            => 'found',
                'title'           => 'Jam Tangan G-Shock Hitam',
                'description'     => 'Jam G-Shock tipe GA-2100 warna full black. Ditemukan di area wudhu.',
                'location'        => 'Area Wudhu Masjid',
                'location_detail' => null,
                'latitude'        => '-7.17530000',
                'longitude'       => '112.64960000',
                'storage_info'    => 'Takmir Masjid',
                'status'          => 'active',
                'date_time'       => '2026-05-06 13:31:33',
                'created_at'      => '2026-05-06 15:31:55',
                'updated_at'      => '2026-05-06 15:31:55',
                '_photos'         => ['items/item_14_watch.jpg'],
            ],
            [
                'id'              => 15,
                'user_id'         => 2,
                'category_id'     => 3,
                'type'            => 'found',
                'title'           => 'Kacamata Rayban Wayfarer',
                'description'     => 'Kacamata hitam Rayban tertinggal di bangku penonton.',
                'location'        => 'Tribun Lapangan Basket',
                'location_detail' => null,
                'latitude'        => '-7.17610000',
                'longitude'       => '112.64870000',
                'storage_info'    => 'Ruang UKM Olahraga',
                'status'          => 'active',
                'date_time'       => '2026-05-04 15:31:33',
                'created_at'      => '2026-05-06 15:31:57',
                'updated_at'      => '2026-05-06 15:31:57',
                '_photos'         => ['items/item_15_sunglasses.jpg'],
            ],
            [
                'id'              => 16,
                'user_id'         => 1,
                'category_id'     => 3,
                'type'            => 'lost',
                'title'           => 'Topi NY Navy',
                'description'     => 'Topi baseball New Era logo NY warna biru dongker.',
                'location'        => 'Kelas Besar GKB 1',
                'location_detail' => null,
                'latitude'        => '-7.17550000',
                'longitude'       => '112.64940000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-05 15:31:33',
                'created_at'      => '2026-05-06 15:31:58',
                'updated_at'      => '2026-05-06 15:31:58',
                '_photos'         => ['items/item_16_cap.jpg'],
            ],
            [
                'id'              => 17,
                'user_id'         => 2,
                'category_id'     => 3,
                'type'            => 'lost',
                'title'           => 'Payung Lipat Hitam',
                'description'     => 'Payung lipat kecil warna hitam polos.',
                'location'        => 'Lobi Gedung C saat hujan',
                'location_detail' => null,
                'latitude'        => '-7.17590000',
                'longitude'       => '112.64890000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-03 15:31:33',
                'created_at'      => '2026-05-06 15:32:01',
                'updated_at'      => '2026-05-06 15:32:01',
                '_photos'         => ['items/item_17_umbrella.jpg'],
            ],
            [
                'id'              => 18,
                'user_id'         => 1,
                'category_id'     => 3,
                'type'            => 'lost',
                'title'           => 'Cincin Emas',
                'description'     => 'Cincin emas polos, ukuran kecil. Jatuh di sekitar koridor.',
                'location'        => 'Koridor Lt 1',
                'location_detail' => null,
                'latitude'        => '-7.17570000',
                'longitude'       => '112.64910000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-06 10:31:33',
                'created_at'      => '2026-05-06 15:32:05',
                'updated_at'      => '2026-05-06 15:32:05',
                '_photos'         => ['items/item_18_ring_jewelry.jpg'],
            ],
            [
                'id'              => 19,
                'user_id'         => 1,
                'category_id'     => 4,
                'type'            => 'lost',
                'title'           => 'Dompet Kulit Coklat',
                'description'     => 'Dompet pria kulit sintesis warna coklat. Isinya KTP, KTM, uang 50rb.',
                'location'        => 'Kantin Sebelah Soto',
                'location_detail' => null,
                'latitude'        => '-7.17600000',
                'longitude'       => '112.64880000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-06 13:31:33',
                'created_at'      => '2026-05-06 15:32:07',
                'updated_at'      => '2026-05-06 15:32:07',
                '_photos'         => ['items/item_19_wallet.jpg'],
            ],
            [
                'id'              => 20,
                'user_id'         => 2,
                'category_id'     => 4,
                'type'            => 'found',
                'title'           => 'Tas Totebag Kanvas Putih',
                'description'     => 'Totebag gambar beruang. Isinya buku tulis dan tempat pensil.',
                'location'        => 'Gazebo Taman',
                'location_detail' => null,
                'latitude'        => '-7.17570000',
                'longitude'       => '112.64910000',
                'storage_info'    => 'Satpam Pos Tengah',
                'status'          => 'active',
                'date_time'       => '2026-05-06 09:31:33',
                'created_at'      => '2026-05-06 15:32:08',
                'updated_at'      => '2026-05-06 15:32:08',
                '_photos'         => ['items/item_20_totebag.jpg'],
            ],
            [
                'id'              => 21,
                'user_id'         => 1,
                'category_id'     => 4,
                'type'            => 'found',
                'title'           => 'Ransel Eiger Hitam',
                'description'     => 'Tas ransel Eiger besar, tertinggal di ruang sidang.',
                'location'        => 'Ruang Sidang Lt 3',
                'location_detail' => null,
                'latitude'        => '-7.17560000',
                'longitude'       => '112.64920000',
                'storage_info'    => 'Admin Jurusan',
                'status'          => 'active',
                'date_time'       => '2026-05-05 15:31:33',
                'created_at'      => '2026-05-06 15:32:11',
                'updated_at'      => '2026-05-06 15:32:11',
                '_photos'         => ['items/item_21_backpack.jpg'],
            ],
            [
                'id'              => 22,
                'user_id'         => 2,
                'category_id'     => 4,
                'type'            => 'lost',
                'title'           => 'Dompet Kartu Cardholder',
                'description'     => 'Cardholder besi warna biru. Isinya kartu debit BCA dan Mandiri.',
                'location'        => 'ATM Center',
                'location_detail' => null,
                'latitude'        => '-7.17630000',
                'longitude'       => '112.64850000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-06 05:31:33',
                'created_at'      => '2026-05-06 15:32:12',
                'updated_at'      => '2026-05-06 15:32:12',
                '_photos'         => ['items/item_22_cardholder.jpg'],
            ],
            [
                'id'              => 23,
                'user_id'         => 1,
                'category_id'     => 5,
                'type'            => 'found',
                'title'           => 'Kunci Motor Vario',
                'description'     => 'Kunci motor Honda Vario dengan gantungan boneka Labubu.',
                'location'        => 'Parkiran Dosen',
                'location_detail' => null,
                'latitude'        => '-7.17520000',
                'longitude'       => '112.64950000',
                'storage_info'    => 'Satpam Parkir',
                'status'          => 'active',
                'date_time'       => '2026-05-06 14:31:33',
                'created_at'      => '2026-05-06 15:32:15',
                'updated_at'      => '2026-05-06 15:32:15',
                '_photos'         => ['items/item_23_keys.jpg'],
            ],
            [
                'id'              => 24,
                'user_id'         => 2,
                'category_id'     => 5,
                'type'            => 'lost',
                'title'           => 'Kunci Mobil Toyota',
                'description'     => 'Kunci mobil remote Toyota (Innova/Avanza) warna hitam.',
                'location'        => 'Lobi Utama',
                'location_detail' => null,
                'latitude'        => '-7.17560000',
                'longitude'       => '112.64920000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-06 12:31:33',
                'created_at'      => '2026-05-06 15:32:16',
                'updated_at'      => '2026-05-06 15:32:16',
                '_photos'         => ['items/item_24_car_key.jpg'],
            ],
            [
                'id'              => 25,
                'user_id'         => 1,
                'category_id'     => 5,
                'type'            => 'found',
                'title'           => 'Kunci Kos (Gembok)',
                'description'     => 'Anak kunci kecil merek Solgen. Gantungan tali hitam.',
                'location'        => 'Tangga Darurat Gedung B',
                'location_detail' => null,
                'latitude'        => '-7.17550000',
                'longitude'       => '112.64940000',
                'storage_info'    => 'Satpam Gedung B',
                'status'          => 'active',
                'date_time'       => '2026-05-04 15:31:33',
                'created_at'      => '2026-05-06 15:32:18',
                'updated_at'      => '2026-05-06 15:32:18',
                '_photos'         => ['items/item_25_padlock_key.jpg'],
            ],
            [
                'id'              => 26,
                'user_id'         => 1,
                'category_id'     => 6,
                'type'            => 'found',
                'title'           => 'Jaket Hoodie H&M',
                'description'     => 'Hoodie warna abu-abu muda ukuran L. Tertinggal di kursi.',
                'location'        => 'Perpus Ruang Baca',
                'location_detail' => null,
                'latitude'        => '-7.17580000',
                'longitude'       => '112.64900000',
                'storage_info'    => 'Loker Penitipan Perpus',
                'status'          => 'active',
                'date_time'       => '2026-05-06 10:31:33',
                'created_at'      => '2026-05-06 15:32:20',
                'updated_at'      => '2026-05-06 15:32:20',
                '_photos'         => ['items/item_26_hoodie.jpg'],
            ],
            [
                'id'              => 27,
                'user_id'         => 2,
                'category_id'     => 6,
                'type'            => 'found',
                'title'           => 'Syal Batik Univ',
                'description'     => 'Syal batik seragam universitas tertinggal setelah acara.',
                'location'        => 'Aula Serbaguna',
                'location_detail' => null,
                'latitude'        => '-7.17550000',
                'longitude'       => '112.64940000',
                'storage_info'    => 'Panitia Acara / Logistik',
                'status'          => 'active',
                'date_time'       => '2026-05-05 15:31:33',
                'created_at'      => '2026-05-06 15:32:23',
                'updated_at'      => '2026-05-06 15:32:23',
                '_photos'         => ['items/item_27_scarf.jpg'],
            ],
            [
                'id'              => 28,
                'user_id'         => 1,
                'category_id'     => 6,
                'type'            => 'lost',
                'title'           => 'Sepatu Futsal Specs',
                'description'     => 'Sepatu futsal warna hijau neon uk 42. Tertinggal di tribun.',
                'location'        => 'Lapangan Futsal',
                'location_detail' => null,
                'latitude'        => '-7.17640000',
                'longitude'       => '112.64840000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-04 15:31:33',
                'created_at'      => '2026-05-06 15:32:27',
                'updated_at'      => '2026-05-06 15:32:27',
                '_photos'         => ['items/item_28_shoes.jpg'],
            ],
            [
                'id'              => 29,
                'user_id'         => 1,
                'category_id'     => 7,
                'type'            => 'found',
                'title'           => 'Tumbler Corkcicle Putih',
                'description'     => 'Botol minum Corkcicle warna putih 16oz. Ada inisial "M".',
                'location'        => 'Meja Dosen R.205',
                'location_detail' => null,
                'latitude'        => '-7.17570000',
                'longitude'       => '112.64910000',
                'storage_info'    => 'Disimpan Dosen (Bu Rina)',
                'status'          => 'active',
                'date_time'       => '2026-05-06 13:31:33',
                'created_at'      => '2026-05-06 15:32:28',
                'updated_at'      => '2026-05-06 15:32:28',
                '_photos'         => ['items/item_29_water_bottle.jpg'],
            ],
            [
                'id'              => 30,
                'user_id'         => 2,
                'category_id'     => 7,
                'type'            => 'lost',
                'title'           => 'Helm KYT Full Face',
                'description'     => 'Helm KYT warna merah motif balap. Hilang di parkiran.',
                'location'        => 'Parkiran Motor Depan',
                'location_detail' => null,
                'latitude'        => '-7.17520000',
                'longitude'       => '112.64950000',
                'storage_info'    => null,
                'status'          => 'active',
                'date_time'       => '2026-05-06 14:31:33',
                'created_at'      => '2026-05-06 15:32:29',
                'updated_at'      => '2026-05-06 15:32:29',
                '_photos'         => ['items/item_30_helmet.jpg'],
            ],
            [
                'id'              => 31,
                'user_id'         => 1,
                'category_id'     => 7,
                'type'            => 'found',
                'title'           => 'Karemt Matras Yoga',
                'description'     => 'Matras yoga warna ungu. Tertinggal habis kegiatan UKM.',
                'location'        => 'Hall Lt 1',
                'location_detail' => null,
                'latitude'        => '-7.17560000',
                'longitude'       => '112.64920000',
                'storage_info'    => 'Sekre UKM Tari',
                'status'          => 'active',
                'date_time'       => '2026-05-03 15:31:33',
                'created_at'      => '2026-05-06 15:32:33',
                'updated_at'      => '2026-05-06 15:32:33',
                '_photos'         => ['items/item_31_yoga_mat.jpg'],
            ],
            [
                'id'              => 32,
                'user_id'         => 2,
                'category_id'     => 7,
                'type'            => 'found',
                'title'           => 'Kotak Makan Tupperware',
                'description'     => 'Kotak makan warna hijau. Isinya sudah kosong.',
                'location'        => 'Meja Taman',
                'location_detail' => null,
                'latitude'        => '-7.17570000',
                'longitude'       => '112.64910000',
                'storage_info'    => 'Tong Sampah (diamankan cleaning service)',
                'status'          => 'active',
                'date_time'       => '2026-05-06 11:31:33',
                'created_at'      => '2026-05-06 15:32:36',
                'updated_at'      => '2026-05-06 15:32:36',
                '_photos'         => ['items/item_32_lunchbox.jpg'],
            ],
            [
                'id'              => 33,
                'user_id'         => 1,
                'category_id'     => 1,
                'type'            => 'found',
                'title'           => 'Flashdisk Sandisk 32GB',
                'description'     => 'Flashdisk merah. Sudah diambil.',
                'location'        => 'Lab',
                'location_detail' => null,
                'latitude'        => '-7.17540000',
                'longitude'       => '112.64930000',
                'storage_info'    => 'Pos Satpam Terdekat',
                'status'          => 'returned',
                'date_time'       => '2026-04-29 15:32:39',
                'created_at'      => '2026-05-06 15:32:39',
                'updated_at'      => '2026-05-06 15:32:39',
                '_photos'         => ['items/item_33_usb_drive.jpg'],
            ],
            [
                'id'              => 34,
                'user_id'         => 2,
                'category_id'     => 5,
                'type'            => 'lost',
                'title'           => 'Kunci Kos',
                'description'     => 'Kunci hilang minggu lalu.',
                'location'        => 'Jalan',
                'location_detail' => null,
                'latitude'        => '-7.17550000',
                'longitude'       => '112.64940000',
                'storage_info'    => null,
                'status'          => 'claimed',
                'date_time'       => '2026-04-26 15:32:46',
                'created_at'      => '2026-05-06 15:32:46',
                'updated_at'      => '2026-05-06 15:32:46',
                '_photos'         => ['items/item_34_keys.jpg'],
            ],
            [
                'id'              => 36,
                'user_id'         => 5,
                'category_id'     => 1,
                'type'            => 'lost',
                'title'           => 'testusbs',
                'description'     => 'testt',
                'location'        => '319, Trate, Kecamatan Gresik, Jawa Timur',
                'location_detail' => 'r3',
                'latitude'        => '-7.16522370',
                'longitude'       => '112.64385260',
                'storage_info'    => null,
                'status'          => 'claimed',
                'date_time'       => '2026-05-20 17:28:00',
                'created_at'      => '2026-05-20 17:28:43',
                'updated_at'      => '2026-05-20 18:15:53',
                '_photos'         => ['items/imDvpNlCVe7oFmQe2reDiUHDkveZP6BnxYX2RX57.jpg', 'items/atusvJ9EoCbZmDfD7hxzFOQ30BzvYuYA6c6nzWVK.jpg', 'items/rHhTOH3sSQKyHHEBUPJlSqCuJNmiLPjMwVpdJugR.jpg'],
            ],
            [
                'id'              => 37,
                'user_id'         => 5,
                'category_id'     => 1,
                'type'            => 'found',
                'title'           => 'laptop',
                'description'     => 'laptop',
                'location'        => '319, Trate, Kecamatan Gresik, Jawa Timur',
                'location_detail' => '2HOS',
                'latitude'        => '-7.16519160',
                'longitude'       => '112.64388580',
                'storage_info'    => 'kubawa',
                'status'          => 'returned',
                'date_time'       => '2026-05-20 17:38:00',
                'created_at'      => '2026-05-20 17:39:31',
                'updated_at'      => '2026-05-20 18:17:15',
                '_photos'         => ['items/PfUpZ8xT0WCQ00dFCLwQfK1RXftUTjcbRpyrWhTj.jpg'],
            ],
            [
                'id'              => 38,
                'user_id'         => 5,
                'category_id'     => 2,
                'type'            => 'found',
                'title'           => 'Buku rahasia',
                'description'     => 'ini buku rahasia',
                'location'        => '319, Trate, Kecamatan Gresik, Jawa Timur',
                'location_detail' => 'hsis',
                'latitude'        => '-7.16522500',
                'longitude'       => '112.64385420',
                'storage_info'    => 'kubawa',
                'status'          => 'active',
                'date_time'       => '2026-05-20 17:53:00',
                'created_at'      => '2026-05-20 17:53:54',
                'updated_at'      => '2026-05-20 17:53:54',
                '_photos'         => ['items/0BJ4lFoyeSaZ2esbW9EmHpYVarhgkaXvKNzg6nXy.jpg'],
            ],
            [
                'id'              => 39,
                'user_id'         => 8,
                'category_id'     => 1,
                'type'            => 'found',
                'title'           => 'jsbej',
                'description'     => 'hebejsej',
                'location'        => '319, Trate, Kecamatan Gresik, Jawa Timur',
                'location_detail' => null,
                'latitude'        => '-7.16522620',
                'longitude'       => '112.64385350',
                'storage_info'    => 'ehejsn',
                'status'          => 'active',
                'date_time'       => '2026-05-20 18:11:00',
                'created_at'      => '2026-05-20 18:12:08',
                'updated_at'      => '2026-05-20 18:12:08',
                '_photos'         => ['items/XLQWyPqDbpRyMm4cwNI3mzKiZO9VmfU4GwiXBi16.jpg'],
            ],
        ];

        foreach ($items as $itemData) {
            $photos = $itemData['_photos'];
            unset($itemData['_photos']);

            DB::table('items')->updateOrInsert(
                ['id' => $itemData['id']],
                $itemData
            );

            foreach ($photos as $photoUrl) {
                DB::table('item_photos')->updateOrInsert(
                    ['item_id' => $itemData['id'], 'photo_url' => $photoUrl],
                    ['item_id' => $itemData['id'], 'photo_url' => $photoUrl, 'created_at' => now(), 'updated_at' => now()]
                );
            }
        }

        // Reset auto-increment sequences
        $maxId = DB::table('items')->max('id') ?? 0;
        $maxPhotoId = DB::table('item_photos')->max('id') ?? 0;
        if (config('database.default') === 'sqlite') {
            DB::statement("UPDATE sqlite_sequence SET seq = $maxId WHERE name = 'items'");
            DB::statement("UPDATE sqlite_sequence SET seq = $maxPhotoId WHERE name = 'item_photos'");
        } elseif (config('database.default') === 'pgsql') {
            DB::statement("SELECT setval(pg_get_serial_sequence('items', 'id'), $maxId)");
            DB::statement("SELECT setval(pg_get_serial_sequence('item_photos', 'id'), $maxPhotoId)");
        }

        // Copy seed images to storage
        $seedImagesPath = database_path('seeders/images/items');
        $storagePath = storage_path('app/public/items');
        if (!is_dir($storagePath)) {
            mkdir($storagePath, 0775, true);
        }
        if (is_dir($seedImagesPath)) {
            foreach (glob("$seedImagesPath/*.jpg") as $file) {
                copy($file, "$storagePath/" . basename($file));
            }
            $this->command->info('Seed images copied to storage/app/public/items/');
        }
    }
}
